import { Inter } from 'next/font/google'
import {Jost} from 'next/font/google'
import { Provider } from 'react'
const inter = Inter({ subsets: ['latin'] })
const jost = Jost({
  subsets: ['latin'],
  weight:['400', '700'],
  veriable:'--font-jost'
})
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jost.veriable}>

{/* <Providers> */}
{/* <Header /> */}
<main className='main'>{children}</main>
{/* <Footer /> */}
{/* </Providers> */}


      </body>
    </html>
  )
}
